yext/visual-editor

THIRD-PARTY-NOTICES
package.json
pnpm-lock.yaml
src/internal/puck/components/Header.tsx
src/internal/puck/ui/switch.tsx

https://github.com/YextSolutions/pages-visual-editor-starter/pull/122
same PR ^

feat: change toggle button to switch

---

package.json
pnpm-lock.yaml
src/components/Editor.tsx
src/internal/puck/components/Header.tsx

feat: remove view page button from header

---

src/utils/resolveVisualEditorData.ts

error was "siteLayoutConfigurations is not iterable"

fix: prevent error in resolveVisualEditorData

---

THIRD-PARTY-NOTICES
package.json
pnpm-lock.yaml
src/components/Editor.tsx
src/internal/components/InternalEditor.tsx
src/internal/puck/components/Header.tsx

Puck updated the api for how `initialHistory` works. Updates were made accordingly.

chore: update to latest Puck canary

---

THIRD-PARTY-NOTICES
src/components/EntityField.tsx

Found out the `<div>` wrapper is needed. I removed in https://github.com/yext/visual-editor/pull/40

fix: wrap EntityField in div

---

.gitignore
THIRD-PARTY-NOTICES

Prevents IntelliJ files from being added to commits

chore: add .idea to .gitignore

---

src/components/YextEntityFieldSelector.tsx
src/utils/resolveYextEntityField.ts

Should make updating existing components to mappable fields more painless

fix: undefined checks for mappable fields

---

src/utils/resolveYextEntityField.ts

makes upgrading repos a little more painless

fix: additional resolveYextEntityField undefined checks

---

src/hooks/index.ts
src/hooks/useEntityFields.tsx
src/internal/types/entityFields.ts
src/utils/getFilteredEntityFields.test.ts
src/utils/getFilteredEntityFields.ts
src/utils/resolveYextEntityField.test.ts
test/dummy.test.ts

This updates bugs found with the field filtering logic while adding tests. Also does a little bit of refactoring.

fix: update field filtering logic

---

THIRD-PARTY-NOTICES
src/utils/resolveVisualEditorData.test.ts
src/utils/resolveVisualEditorData.ts

Use built-in fields in VisualEditor
Updates ResolveVisualEditorData to match the new fields
Adds test for resolveVisualEditorData

feat(util): use built-in fields

---

src/utils/resolveVisualEditorData.ts

Unfortunately the _site object cannot be overridden directly by the preview endpoint. As a workaround, a new key is added to the document which we look for in the resolveVisualEditorData function.

feat: add theme preview support

---

src/components/puck/atoms/index.ts
src/components/puck/atoms/myAtom.tsx
src/components/puck/myPuck.tsx

refactor: cleanup components

---

src/components/puck/HeadingText.tsx
src/components/puck/atoms/heading.tsx
src/components/puck/index.css

fixed some tailwind not working due to lack of "ve-" prefix
changed size from select to number

fix: header component

---

src/components/puck/BodyText.tsx
src/components/puck/atoms/body.tsx
src/components/puck/index.ts

Tested with a local VE build in dev mode and the component worked as expected.

feat: add body text component

---

src/components/editor/YextEntityFieldSelector.tsx
src/internal/puck/constant-value-fields/Address.tsx
src/internal/puck/constant-value-fields/Image.tsx
src/internal/puck/constant-value-fields/Text.tsx

feat: support address constant values

---

src/components/editor/YextEntityFieldSelector.tsx
src/components/puck/BodyText.tsx
src/components/puck/HeadingText.tsx
src/components/puck/Image.tsx
src/utils/resolveYextEntityField.ts

Includes updates to the components that live in VE
The starter components will also need to be updated in a similar manner

feat: add generic support for constant value

---

THIRD-PARTY-NOTICES
pnpm-lock.yaml
src/components/editor/EntityField.test.tsx
src/components/editor/EntityField.tsx
src/components/puck/BodyText.tsx
src/components/puck/HeadingText.tsx
src/components/puck/Image.tsx

feat: change entity tooltip to just fieldId

---

THIRD-PARTY-NOTICES
src/components/editor/YextEntityFieldSelector.tsx
src/internal/puck/constant-value-fields/TextList.tsx

This change allows for a list of constant text values to be assigned to a TextList component. Deleting values, creating new values, and editing existing ones all work correctly.

feat: correctly support constant values for text lists

---

THIRD-PARTY-NOTICES
src/internal/utils/getFilteredEntityFields.ts

Needed for GetDirections component

feat: add coordinate type EntityFieldTypes

---

THIRD-PARTY-NOTICES
package.json
pnpm-lock.yaml
src/components/puck/GetDirections.tsx
src/components/puck/index.ts

tested manually with https://dev.yext.com/s/1000146856/yextsites/63179/editor#templateId=location&layoutId=8747046&view=EDIT&entityId=8694637

feat: add GetDirections component

---

src/utils/resolveVisualEditorData.ts

If there is no siteId on the document then siteId is ignored.

feat: handle siteId in resolveVisualEditorData

---

src/components/editor/EntityField.test.tsx
src/components/editor/NumberOrDefaultField.tsx
src/components/editor/index.ts
src/components/puck/BodyText.tsx
src/components/puck/CtaWrapper.tsx
src/components/puck/HeadingText.tsx
src/components/puck/atoms/body.tsx
src/components/puck/atoms/button.tsx
src/components/puck/atoms/cta.tsx
src/components/puck/atoms/heading.tsx
src/index.ts

Used in the components to set font size, should work for other number values like padding or border radius if wanted
https://github.com/user-attachments/assets/a0c4e31e-b03b-429b-a997-077455e0f5c3

feat: add NumberOrDefaultField

---

src/components/puck/GetDirections.tsx
src/components/puck/atoms/button.tsx

Prevents build error for missing fontSize prop

feat: add fontSize to getDirections

---

src/components/puck/Phone.tsx

Add phone icon + domestic / international option.
Works with 1-3 digit international codes.
Phone icon changes size with font size

fix: adjust phone component

---

src/components/puck/Emails.tsx

fix: adjust email padding

---

src/components/puck/CtaWrapper.tsx
src/components/puck/GetDirections.tsx
src/components/puck/atoms/button.tsx

With this [PR](https://github.com/YextSolutions/pages-visual-editor-starter/pull/170)

feat: add additional button tw from theme 

---

src/components/editor/YextEntityFieldSelector.tsx
src/components/puck/CtaWrapper.tsx
src/components/puck/atoms/cta.tsx
src/internal/puck/constant-value-fields/Address.tsx
src/internal/puck/constant-value-fields/CallToAction.tsx
src/internal/puck/constant-value-fields/ConstantField.tsx
src/internal/puck/constant-value-fields/Image.tsx
src/internal/utils/getFilteredEntityFields.ts

Constant value includes name and url fields
Tested on dev account
Verified that constant values can be set properly

feat: add constant value support for CTA

---

src/internal/components/ThemeEditor.tsx
src/internal/hooks/useMessageReceivers.ts

puckInitialHistoryFetched was never set to true in dev theme mode

fix: theme manager dev mode stuck loading

---

pnpm-lock.yaml
src/internal/components/ThemeEditor.tsx
src/internal/components/atoms/Alert.tsx
src/internal/puck/components/ThemeSidebar.tsx
src/internal/puck/ui/puck.css

feat: add collapsible theme

---

pnpm-lock.yaml
src/components/puck/GetDirections.tsx

Remove icon from button size options

fix: adjust Get Directions component 

---

THIRD-PARTY-NOTICES
package.json
pnpm-lock.yaml

This canary includes my fix for leading zeros in NumberFields

chore: upgrade puck

---

src/components/puck/HoursTable.tsx
src/components/puck/index.ts

HoursCard was renamed to HoursTable in #153 but then the file was accidentally renamed back to HoursCard in #142

fix: rename HoursTable again

---

src/components/editor/YextEntityFieldSelector.tsx

Puck 0.17 broke our entity field selection -- it introduced useMemo to Array and Radio fields but not the other field types. When switching between field types via the ternary operator, React crashed due to mismatched hook counts between renders. By encapsulating the <AutoField> calls within their own components, React handles the hooks correctly.

fix: entity field selection

---

src/components/editor/YextEntityFieldSelector.tsx
src/components/puck/Card.tsx
src/components/puck/atoms/heading.tsx

Fixes several issues with the Card component
Adds a level selector and background color selector to the card component
Verified that changing the level changes the size of text according to what is in the theme for Heading 1, Heading 2, etc
Color selector works as expected
Fixes an issue where changing "constant value" mode of one field would change the setting on another

fix: card component fixes

---

src/components/editor/YextEntityFieldSelector.tsx
src/internal/puck/constant-value-fields/ConstantField.tsx
src/internal/puck/constant-value-fields/Phone.tsx
src/internal/puck/constant-value-fields/TextList.tsx
src/internal/puck/ui/label.tsx

~~Will send to Aaron for UI approval~~  👍
Text - Entity Field
Text - Constant Value
Phone - Entity Field
Phone - Constant Value
Image - Entity Field
Image - Constant Value
Address - Entity Field
Address - Constant Value
Call to Action - Entity Field
Call to Action - Constant Value
Text List - Entity Field
Text List - Constant Value
Hide "Constant Value" option for field types that do not have a constant value input

refactor: update constant value field styling

---

src/components/puck/Address.tsx

Added "Show Directions" toggle
Removed provider option. Default to Google

feat: address component updates

---

src/utils/README.md
src/utils/index.ts
src/utils/slugifier.test.ts
src/utils/slugifier.ts

feat: normalizeSlug

---

src/components/puck/Banner.tsx
src/components/puck/FlexContainer.tsx
src/components/puck/GridSection.tsx

- Disallow Banner in Grid/Flex
- Text color and background color as dropdowns

refactor: banner component updates

---

packages/visual-editor/THIRD-PARTY-NOTICES
packages/visual-editor/package.json
pnpm-lock.yaml
starter/package.json

Tested all the components as well as new DragAndDrop functionality. 
Tested [here](https://www.yext.com/s/4174974/yextsites/153548/pagesets)

chore: upgrade puck to v0.18.0

---

packages/visual-editor/THIRD-PARTY-NOTICES
packages/visual-editor/package.json
pnpm-lock.yaml
starter/package.json

Tested all components and confirmed no issues appeared.

chore: update to puck v0.18.1

---

packages/visual-editor/THIRD-PARTY-NOTICES
packages/visual-editor/package.json
packages/visual-editor/src/internal/components/InternalLayoutEditor.tsx
packages/visual-editor/src/internal/components/InternalThemeEditor.tsx
packages/visual-editor/src/internal/components/LayoutEditor.tsx
packages/visual-editor/src/internal/components/ThemeEditor.tsx
pnpm-lock.yaml

Verified that dev mode local storage loads as expected.
Refreshing page and toggling between theme and layout mode works normally.

feat(deps): add lz-compression for local storage

---

packages/visual-editor/package.json
packages/visual-editor/src/components/puck/Emails.tsx
pnpm-lock.yaml
starter/package.json

All other components are already using <Link>
Verified that emails component works as expected.

feat: update Emails to use Link component

---

packages/visual-editor/src/components/puck/Footer.tsx

If we have a Twitter handle that doesn't start with twitter.com/, then we prepend it
Same for the other social fields

feat: prepend prefix to social fields

---

packages/visual-editor/src/internal/puck/components/LayoutHeader.tsx
packages/visual-editor/src/internal/puck/components/ThemeHeader.tsx
packages/visual-editor/src/internal/puck/ui/UIButtonsToggle.tsx

Tested with pnpm run dev and verified left toggle/side bar is removed

feat: remove left toggle for theme manager

---

starter/src/components/Locator.tsx
starter/src/ve.config.tsx

Barebones skeleton for the Locator component

feat: skeleton for Locator component

---

pnpm-lock.yaml
starter/package.json
starter/src/components/Locator.tsx

This PR inserts a basic FilterSearch bar into the Locator component. It does not do anything with the results. 
J=WAT-4698
TEST=manual
Ran locally and saw filter searches execute

feat: add FilterSearch Bar for Locator component

---

packages/visual-editor/src/components/puck/Banner.tsx

Test locally, will need to update the colors after theme updates

feat: banner component update

---

packages/visual-editor/src/components/puck/Address.tsx

feat: update address component

---

packages/visual-editor/src/components/puck/HoursStatus.tsx

tested locally and verified that the font is now h5

feat: update hours status component

---

packages/visual-editor/src/components/puck/Directory.tsx
packages/visual-editor/src/components/puck/Flex.tsx
packages/visual-editor/src/components/puck/Grid.tsx
packages/visual-editor/src/components/puck/HoursStatus.tsx
packages/visual-editor/src/components/puck/Layout.tsx
packages/visual-editor/src/components/puck/atoms/heading.tsx
packages/visual-editor/src/utils/README.md
starter/theme.config.ts

Aligns the colors, headings, body and page sections of the theme config with the document. Also updates of the heading variables.
Usages of colors and body styles will need to be fixed in a future PR following the addition of auto-gen colors and body styles (I will work on that next). The section component (and Flex and Grid) will need some updates as well, since we no longer set gap and have different padding types.

refactor: new theme config

---

packages/visual-editor/src/components/puck/GetDirections.tsx

This removes styling props from the GetDirections component.

feat: update GetDirections component

---

packages/visual-editor/src/components/puck/HoursTable.tsx

feat: remove padding option from hours table

---

starter/localData/dev-dm-city-stream__en__8932945.json
starter/localData/dev-dm-country-stream__en__8932938.json
starter/localData/dev-dm-region-stream__en__8932944.json
starter/localData/dev-dm-root-stream__en__8932937.json
starter/localData/dev-location-stream__en__8573da7e3961090ddb59214a1f01e59a.json
starter/localData/dev-location-stream__en__a5ac5ff0d6330870779568c3bc865bc7.json
starter/localData/dev-location-stream__en__aa6fc9407fdca53fc4133ee078b93231.json
starter/localData/dev-location-stream__en__cbafb9cd1c3e63d9814e236ba9181377.json
starter/localData/dev-location-stream__en__d7f52f17aa2a321e60e8c1a8fae53637.json
starter/localData/dev-location-stream__en__fd8e569c314d912412add63bb882142c.json

Adds test data to support header, footer, directory, and breadcrumbs

chore: add dm and site data

---

packages/visual-editor/src/components/puck/Flex.tsx

This replaces the direction, justify content, and wrap selectors to radios. The spacing options have already been updated to only show the px value in the options.

feat: flex component updates

---

packages/visual-editor/src/components/puck/Footer.tsx

Did not adjust theme or tailwind styling at all as that is done in #299 
Will wait to merge until after #299 is merged

feat: add color dropdown to Footer

---

packages/visual-editor/src/components/puck/TestimonialCard.tsx
packages/visual-editor/src/components/puck/Testimonials.tsx
packages/visual-editor/src/components/puck/index.ts
packages/visual-editor/src/components/puck/registry/components.ts
starter/src/ve.config.tsx

feat: add testimonials component

---

packages/visual-editor/src/internal/puck/ui/Combobox.tsx

fix: color sector selected color

---

packages/visual-editor/src/components/editor/FontSizeSelector.tsx
packages/visual-editor/src/utils/themeConfigOptions.ts
starter/theme.config.ts

Brings the font sizes inline with the mock

fix: default heading text font sizes

---

packages/visual-editor/src/components/puck/Events.tsx
packages/visual-editor/src/components/puck/index.ts
packages/visual-editor/src/components/puck/registry/components.ts
starter/src/ve.config.tsx

feat: add Events component

---

packages/visual-editor/src/components/puck/HoursStatus.tsx

Use radio instead of a selector for "Day of Week Format"

feat: update hours "dayOfWeekFormat" to use radio

---

packages/visual-editor/src/components/editor/YextEntityFieldSelector.tsx

Updates to use the BasicSelector instead of standard Select for Entity Fields

feat: use BasicSelector for EntityFields

---

packages/visual-editor/src/components/puck/NearbyLocations.tsx

The cards are now all the same height and the corners appear rounded properly.
Latest:

feat: update NearbyLocations to use new Section styling

---

packages/visual-editor/src/components/puck/Collection.tsx
packages/visual-editor/src/components/puck/cards/ProductCard.tsx

refactor: adjust collections / product cards

---

packages/visual-editor/src/components/puck/SectionContainer.tsx

feat: add prop to section component

---

packages/visual-editor/src/components/puck/MapboxStaticMap.tsx

Updates mapbox static map size to fit the container
Inside of a Grid
Inside of a Flex
Inside of Section Container

feat: dynamically set mapbox static map size

---

packages/visual-editor/package.json
packages/visual-editor/src/vite-plugin/plugin.ts
packages/visual-editor/src/vite-plugin/templates/main.tsx

Updated main.tsx template and confirmed dev mode and production builds work

fix: update yextVisualEditorPlugin

---

packages/visual-editor/src/components/CoreInfoSection.tsx

fix: correct column spacing for core info section

---

packages/visual-editor/src/components/cards/InsightCard.tsx
packages/visual-editor/src/components/cards/PersonCard.tsx
packages/visual-editor/src/components/cards/ProductCard.tsx
packages/visual-editor/src/components/cards/TestimonialCard.tsx
packages/visual-editor/src/components/layoutBlocks/Collection.tsx

removed line-clamps and instead card heights to match other cards.

fix: card heights adjust

---

packages/visual-editor/src/components/Footer.tsx
packages/visual-editor/src/components/Header.tsx

Hides links in the Header and Footer components if the Link is not set

fix: hide header/footer links if Link is not set

---

packages/visual-editor/src/components/layoutBlocks/Flex.tsx

https://jam.dev/c/d24a196c-125a-426e-aeec-18c1fe18c291
Aaron requested.

feat: add alignItems to flex

---

packages/visual-editor/src/components/pageSections/FAQs.tsx
packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
packages/visual-editor/src/editor/YextField.tsx

https://jam.dev/c/4f76c648-74ce-4cea-b784-69f3e88fa4d5

feat: adjust FAQsSection into Collection

---

packages/visual-editor/src/components/_componentCategories.ts
starter/src/ve.config.tsx

feat: remove content, layout, card categories

---

packages/visual-editor/src/components/_componentCategories.ts
packages/visual-editor/src/components/contentBlocks/MapboxStaticMap.tsx
packages/visual-editor/src/components/pageSections/StaticMapSection.tsx

feat: add staticMapSection

---

packages/visual-editor/src/components/atoms/timestamp.test.tsx
packages/visual-editor/src/components/atoms/timestamp.tsx

> Multi-days events: MM DD, YYYY - MM DD, YYYY | 00:00 AM - 00:00 PM
> Single day event: MM DD, YYYY | 00:00 AM - 00:00 PM
> Published Date: MM DD, YYYY
per: https://yext.slack.com/archives/C06A06BCUUF/p1746456603802529?thread_ts=1746454986.150349&cid=C06A06BCUUF

fix: update timestamp

---

packages/visual-editor/src/components/_componentCategories.ts
packages/visual-editor/src/components/pageSections/EventSection.test.tsx
packages/visual-editor/src/components/pageSections/EventSection.tsx
packages/visual-editor/src/components/pageSections/index.ts
packages/visual-editor/src/internal/utils/getFilteredEntityFields.ts

feat: add EventSection component

---

packages/visual-editor/src/components/_componentCategories.ts
packages/visual-editor/src/components/pageSections/TeamSection.test.tsx
packages/visual-editor/src/components/pageSections/TeamSection.tsx
packages/visual-editor/src/components/pageSections/index.ts
packages/visual-editor/src/internal/utils/getFilteredEntityFields.ts

fixed label on Data to Data instead of Section Heading lol

feat: add TeamSection component

---

packages/visual-editor/src/components/pageSections/InsightSection.test.tsx
packages/visual-editor/src/components/pageSections/InsightSection.tsx
packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/InsightSection.tsx
packages/visual-editor/src/types/types.ts

feat: insight section const value support

---

packages/visual-editor/src/components/pageSections/FAQsSection.test.tsx
packages/visual-editor/src/components/pageSections/FAQsSection.tsx
packages/visual-editor/src/components/pageSections/ProductSection.tsx
packages/visual-editor/src/components/registry/components.ts
packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/FAQsSection.tsx
packages/visual-editor/src/types/types.ts

feat: add const support for faqs section

---

packages/visual-editor/src/components/pageSections/TeamSection.test.tsx
packages/visual-editor/src/components/pageSections/TeamSection.tsx
packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/TeamSection.tsx

feat: support const values for team section

---

packages/visual-editor/src/components/atoms/timestamp.tsx
packages/visual-editor/src/components/pageSections/TestimonialSection.test.tsx
packages/visual-editor/src/components/pageSections/TestimonialSection.tsx
packages/visual-editor/src/components/registry/components.ts
packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
packages/visual-editor/src/internal/puck/components/DateSelector.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/InsightSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/TestimonialSection.tsx
packages/visual-editor/src/types/types.ts

feat: add const value support for testimonials section

---

starter/localData/dev-location-stream__en__8573da7e3961090ddb59214a1f01e59a.json
starter/localData/dev-location-stream__en__a5ac5ff0d6330870779568c3bc865bc7.json
starter/localData/dev-location-stream__en__aa6fc9407fdca53fc4133ee078b93231.json
starter/localData/dev-location-stream__en__cbafb9cd1c3e63d9814e236ba9181377.json
starter/localData/dev-location-stream__en__d7f52f17aa2a321e60e8c1a8fae53637.json
starter/src/dev.config.ts

Adds test data for the page sections. Data was created in KG and copied into the starter. Also removes some old field types our components no longer support. Will want to change RTF json to html once that's working

chore: update test data

---

packages/visual-editor/THIRD-PARTY-NOTICES
packages/visual-editor/package.json
packages/visual-editor/src/internal/components/InternalLayoutEditor.tsx
packages/visual-editor/src/internal/components/LayoutEditor.tsx
packages/visual-editor/src/internal/components/modals/ApprovalModal.tsx
packages/visual-editor/src/internal/components/modals/LayoutApprovalModal.tsx
packages/visual-editor/src/internal/hooks/layout/useMessageSenders.ts
packages/visual-editor/src/internal/puck/components/LayoutHeader.tsx
packages/visual-editor/src/internal/types/templateMetadata.ts
pnpm-lock.yaml

Adds a modal that opens for the Send for Approval flow
This modal will be opened by clicking "Send for Approval"
Send for Approval replaces Publish when in ENTITY assignment mode
Updated [05 15 2025]

feat: add modal for Send for Approval flow

---

packages/visual-editor/src/editor/YextEntityFieldSelector.tsx

https://jam.dev/c/cef9ba09-557c-4bd2-a404-0b6cc3255798

feat: update text and tooltip for YextEntityFieldSelector

---

packages/visual-editor/src/internal/puck/components/FontSelector.tsx
packages/visual-editor/src/internal/puck/ui/puck.css

https://github.com/user-attachments/assets/ba9b38b0-611e-4ad9-800d-59e1df0eff16

feat: font search

---

packages/visual-editor/src/internal/components/InternalThemeEditor.tsx
packages/visual-editor/src/internal/puck/components/LayoutHeader.tsx
packages/visual-editor/src/internal/puck/components/ThemeHeader.tsx
packages/visual-editor/src/internal/types/templateMetadata.ts

Corresponding CR on the storm size to include the page count in the message.

feat: update publish to update pages

---

.github/workflows/check-migrations.yml
packages/visual-editor/src/components/pageSections/TestimonialSection.tsx

refactor: only comment migration warning once

---

packages/visual-editor/src/vite-plugin/plugin.ts

This is the only difference with the manifest currently in the starter

fix: update template manifest description

---

packages/visual-editor/src/components/pageSections/CoreInfoSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/CallToAction.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/EventSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/FAQsSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/InsightSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/ProductSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/TeamSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/TestimonialSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/Text.tsx
packages/visual-editor/src/utils/generateTranslatableConfig.tsx
packages/visual-editor/src/utils/index.ts

Translates the phone label in CoreInfoSection

feat: translate Phone label for CoreInfoSection

---

packages/visual-editor/package.json
packages/visual-editor/src/components/Locator.tsx
packages/visual-editor/src/components/atoms/phone.tsx
pnpm-lock.yaml
starter/package.json

TEST=manual
tested in dev mode and verified that:
- the phone number, Get Directions, and Visit Page buttons appear the same as before
- analytics events have the expected payload in network tab and snowflake

feat: support analytics events for locator

---

packages/visual-editor/src/components/pageSections/EventSection.tsx
packages/visual-editor/src/components/pageSections/FAQsSection.tsx
packages/visual-editor/src/components/pageSections/InsightSection.tsx
packages/visual-editor/src/components/pageSections/ProductSection.tsx
packages/visual-editor/src/components/pageSections/TeamSection.tsx
packages/visual-editor/src/components/pageSections/TestimonialSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/EventSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/FAQsSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/InsightSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/ProductSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/TeamSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/TestimonialSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/TextList.tsx

https://jam.dev/c/84d96b29-565d-470b-87fb-d596c518785e
Wasn't there before but now when u add new "cards", they look nicer / not empty.
(and i need hasLocalizedValues)

feat: add defaultProps to arrays 

---

packages/visual-editor/src/editor/BasicSelector.tsx
packages/visual-editor/src/editor/YextEntityFieldSelector.tsx

https://yext.slack.com/archives/C06A06BCUUF/p1749829398799859

refactor: remove chevron from entity field selector

---

packages/visual-editor/src/editor/YextStructFieldSelector.tsx
packages/visual-editor/src/internal/components/LayoutEditor.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/InsightSection.tsx

- Fixes a React key warning
- Fixes a date formatting warning
- Migrates localstorage when using proxied dev mode

fix: react warnings and proxied dev migrations

---

packages/visual-editor/src/components/pageSections/Banner.tsx

feat: hide banner if missing data

---

packages/visual-editor/src/internal/puck/ui/Combobox.tsx

https://github.com/user-attachments/assets/e408f60c-5900-4cb0-926f-31594b2aaa17
~~Waiting on confirmation from https://yext.slack.com/archives/C06A06BCUUF/p1751400636055309~~ Confirmed

fix: truncate strings in BasicSelector

---

packages/visual-editor/src/components/atoms/image.tsx
packages/visual-editor/src/components/contentBlocks/Image.tsx
packages/visual-editor/src/components/contentBlocks/ImageStyling.tsx
packages/visual-editor/src/components/header/Header.tsx
packages/visual-editor/src/components/migrations/0006_update_image_styling.ts
packages/visual-editor/src/components/migrations/migrationRegistry.ts
packages/visual-editor/src/components/pageSections/EventSection.tsx
packages/visual-editor/src/components/pageSections/HeroSection.tsx
packages/visual-editor/src/components/pageSections/InsightSection.tsx
packages/visual-editor/src/components/pageSections/PhotoGallerySection.tsx
packages/visual-editor/src/components/pageSections/ProductSection.tsx
packages/visual-editor/src/components/pageSections/PromoSection.tsx
packages/visual-editor/src/components/pageSections/TeamSection.tsx
packages/visual-editor/src/internal/puck/constant-value-fields/ImageList.tsx
packages/visual-editor/src/types/types.ts

https://github.com/user-attachments/assets/0f1a388d-852d-4c41-b358-ceeb337e8843

feat: add image styling props

---

packages/visual-editor/package.json
packages/visual-editor/src/components/header/Header.tsx
packages/visual-editor/src/components/pageSections/FAQsSection.tsx
pnpm-lock.yaml
starter/package.json

Confirmed the analytics events made it to snowflake, will check in report builder later. 
I'll also add to the Reviews component once it is ready, in the meantime I'll keep the JIRA item open

feat: add non-link analytics to FAQ section and mobile header

---

packages/visual-editor/locales/ja/visual-editor.json
packages/visual-editor/package.json
packages/visual-editor/src/components/Locator.tsx
pnpm-lock.yaml

Strings in search-ui-react components will be translated after this change. 
Tested in platform and saw the near me button label ("Current Location") properly translated.

chore: upgrade search-ui-react for more translations

---

packages/visual-editor/src/components/ExpandedFooter.tsx
packages/visual-editor/src/components/header/ExpandedHeader.tsx
packages/visual-editor/src/components/header/languageDropdown.tsx

- fixes document is undefined
- fixes language dropdown styling
- fixes default link props
https://github.com/user-attachments/assets/1d0b8d98-c13c-44ce-9f8c-38ecf007785a

fix: language dropdown fails page generation

---

packages/visual-editor/src/vite-plugin/templates/directory.tsx
packages/visual-editor/src/vite-plugin/templates/locator.tsx
packages/visual-editor/src/vite-plugin/templates/main.tsx
starter/localData/dev-dm-city-stream__en__8932945.json
starter/localData/dev-dm-region-stream__en__8932944.json
starter/localData/dev-dm-root-stream__en__8932937.json
starter/localData/dev-location-stream__en__8573da7e3961090ddb59214a1f01e59a.json
starter/localData/dev-location-stream__en__a5ac5ff0d6330870779568c3bc865bc7.json
starter/localData/dev-location-stream__en__aa6fc9407fdca53fc4133ee078b93231.json
starter/localData/dev-location-stream__en__cbafb9cd1c3e63d9814e236ba9181377.json
starter/localData/dev-location-stream__en__d7f52f17aa2a321e60e8c1a8fae53637.json
starter/localData/dev-location-stream__es__cbafb9cd1c3e63d9814e236ba9181377.json
starter/localData/dev-location-stream__zh_hans_hk__cbafb9cd1c3e63d9814e236ba9181377.json

Works with new favicon (Spruce made) as long as you make a new deploy after adding the favicon.

feat: use favicon from document

---

packages/visual-editor/src/components/Directory.tsx
packages/visual-editor/src/components/Locator.tsx
packages/visual-editor/src/components/footer/Footer.tsx
packages/visual-editor/src/components/header/ExpandedHeader.tsx
packages/visual-editor/src/components/header/Header.tsx
packages/visual-editor/src/components/pageSections/Banner.tsx
packages/visual-editor/src/components/pageSections/Breadcrumbs.tsx
packages/visual-editor/src/components/pageSections/CoreInfoSection.tsx
packages/visual-editor/src/components/pageSections/EventSection.tsx
packages/visual-editor/src/components/pageSections/FAQsSection.tsx
packages/visual-editor/src/components/pageSections/InsightSection.tsx
packages/visual-editor/src/components/pageSections/NearbyLocations.tsx
packages/visual-editor/src/components/pageSections/PhotoGallerySection.tsx
packages/visual-editor/src/components/pageSections/ProductSection.tsx
packages/visual-editor/src/components/pageSections/PromoSection.tsx
packages/visual-editor/src/components/pageSections/StaticMapSection.tsx
packages/visual-editor/src/components/pageSections/TeamSection.tsx
packages/visual-editor/src/components/pageSections/TestimonialSection.tsx
packages/visual-editor/src/docs/components.md
packages/visual-editor/src/docs/hybrid-development.md
packages/visual-editor/src/utils/visualEditorFonts.ts

This PR fixes a typo found in a couple places in the repo, mostly in comments.
J=none
TEST=none

fix: typos

---

packages/visual-editor/src/components/layoutBlocks/Grid.tsx

https://github.com/user-attachments/assets/a7fa6de4-49af-42b6-a97f-b7bfb5b84d49

refactor: use slots for grid

---

packages/visual-editor/locales/cs/visual-editor.json
packages/visual-editor/locales/da/visual-editor.json
packages/visual-editor/locales/de/visual-editor.json
packages/visual-editor/locales/en-GB/visual-editor.json
packages/visual-editor/locales/en/visual-editor.json
packages/visual-editor/locales/es/visual-editor.json
packages/visual-editor/locales/et/visual-editor.json
packages/visual-editor/locales/fi/visual-editor.json
packages/visual-editor/locales/fr/visual-editor.json
packages/visual-editor/locales/hr/visual-editor.json
packages/visual-editor/locales/hu/visual-editor.json
packages/visual-editor/locales/it/visual-editor.json
packages/visual-editor/locales/ja/visual-editor.json
packages/visual-editor/locales/lt/visual-editor.json
packages/visual-editor/locales/lv/visual-editor.json
packages/visual-editor/locales/nb/visual-editor.json
packages/visual-editor/locales/nl/visual-editor.json
packages/visual-editor/locales/pl/visual-editor.json
packages/visual-editor/locales/pt/visual-editor.json
packages/visual-editor/locales/ro/visual-editor.json
packages/visual-editor/locales/sk/visual-editor.json
packages/visual-editor/locales/sv/visual-editor.json
packages/visual-editor/locales/tr/visual-editor.json
packages/visual-editor/locales/zh-TW/visual-editor.json
packages/visual-editor/locales/zh/visual-editor.json
packages/visual-editor/src/editor/BasicSelector.tsx
packages/visual-editor/src/editor/YextEntityFieldSelector.tsx

https://yext.slack.com/archives/C06A06BCUUF/p1754496210005529

feat: use entity type name in field selector

---

packages/visual-editor/locales/cs/visual-editor.json
packages/visual-editor/locales/da/visual-editor.json
packages/visual-editor/locales/de/visual-editor.json
packages/visual-editor/locales/en-GB/visual-editor.json
packages/visual-editor/locales/en/visual-editor.json
packages/visual-editor/locales/es/visual-editor.json
packages/visual-editor/locales/et/visual-editor.json
packages/visual-editor/locales/fi/visual-editor.json
packages/visual-editor/locales/fr/visual-editor.json
packages/visual-editor/locales/hr/visual-editor.json
packages/visual-editor/locales/hu/visual-editor.json
packages/visual-editor/locales/it/visual-editor.json
packages/visual-editor/locales/ja/visual-editor.json
packages/visual-editor/locales/lt/visual-editor.json
packages/visual-editor/locales/lv/visual-editor.json
packages/visual-editor/locales/nb/visual-editor.json
packages/visual-editor/locales/nl/visual-editor.json
packages/visual-editor/locales/pl/visual-editor.json
packages/visual-editor/locales/pt/visual-editor.json
packages/visual-editor/locales/ro/visual-editor.json
packages/visual-editor/locales/sk/visual-editor.json
packages/visual-editor/locales/sv/visual-editor.json
packages/visual-editor/locales/tr/visual-editor.json
packages/visual-editor/locales/zh-TW/visual-editor.json
packages/visual-editor/locales/zh/visual-editor.json
packages/visual-editor/src/components/header/ExpandedHeader.tsx
packages/visual-editor/src/docs/components.md

Adds a "Fixed" option in addition to "Scrolls with Page" and "Sticky"
For this option, we need to use a ref to dynamically determine the height of the header and create space for it.

feat: add Fixed option for Expanded Header

---

packages/visual-editor/src/components/footer/Footer.test.tsx

Seems to be a common source of flakiness recently

chore: ignore flaky footer change

---

packages/visual-editor/src/components/Locator.tsx

fix: locator no results mobile width
