src/components/Editor.tsx
Verified that VE works in storm in multiple envs (where ancestor origin contains pagescdn or yext.com), verified that running VE on localhost redirects to 404 and that no content loads prior to the redirect.
=> feat: redirect to 404.html if origin is not in storm

src/components/Editor.tsx, src/internal/components/InternalEditor.tsx, src/internal/puck/components/Header.tsx
[SUMO-6143](https://yexttest.atlassian.net/browse/SUMO-6143?atlOrigin=eyJpIjoiZGI5NTk1ZmUzOTE2NGZlNGEzYTdmN2UwZjc2N2EzYzEiLCJwIjoiaiJ9)
This fixes the Clear Local Changes button to:
1. Close the modal on confirmation
2. Reset the Puck data state without a page refresh
Additionally, this fixes the undo button to properly undo to the original state before there were any changes instead of getting stuck at the first change.
=> fix:  update Puck after clearing local changes and fix undo state

src/components/EntityField.tsx
```react-dom@18.2.0.development.js:73 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? Check the render method of `Tooltip`. at DevLivePreviewGenerator```
=> fix: remove tooltip warning 

src/components/Editor.tsx, src/internal/components/InternalEditor.tsx, src/internal/types/templateMetadata.ts
Adds functionality for `devOverride` coming through with templateMetadata. It can be enabled through a query param and allows dev mode to operate like normal prod mode (apart from the preview functionality). The main use case is to debug Storm/VE issues while in dev mode without needing to comment out a bunch of dev-specific code.
Also added some cleanup of getting the localStorageKey to be less redundant.
=> feat: add devOverride functionality

src/components/Editor.tsx
We were auto redirecting to 404 on localhost which made local development not work in Yext dev.
=> fix: redirecting on localhost

THIRD-PARTY-NOTICES, src/components/Editor.tsx
Adds event listeners for cmd+k and ctrl+k. When triggered, sends a message to the parent (storm).
Adds support for the shortcut when the header or sidebars are selected. Still does not work on the puck preview iframe because we cannot add a listener to that iframe from outside the puck package.
=> fix: make quick find keyboard shortcut work

src/internal/hooks/useMessage.ts
There is a case where I see a `MessageEvent` with an origin, source, and null data. In this case the origin is not a target origin, but the code errors out on the null data first before it can throw a "Unrecognized origin" error.
=> fix: add null check to message.data

src/components/Editor.tsx
- reads siteStream global variable from pages.js
- passes siteStream to Storm
- upcoming update to storm will use this to return `_site` in dev mode
- together with [https://github.com/yext/pages/pull/542](https://github.com/yext/pages/pull/542)
=> fix: make _site object available on documents in dev mode

src/components/Editor.tsx
`loadPuckInitialHistory()` was called when `visualConfigurationData` updated, but sometimes it would immediate return because `visualConfigurationDataFetched` was false, causing the puck history to never load.
Since `setVisualConfigurationData()` & `setVisualConfigurationDataFetched()` are called in the same function, this case would sometimes happen.
Switched the `useEffect` for  `loadPuckInitialHistory()` to watch for `saveStateFetched` and `visualConfigurationDataFetched` to avoid this condition.
=> fix: loadPuckInitialHistory is never called

src/hooks/README.md, src/hooks/index.ts, src/hooks/useEntityFields.tsx
Adds `usePlatformBridgeEntityFields`, `EntityFieldsProvider`, and `useEntityFields`. These are used to support mappable entity fields in the Puck props.
=> feat: add hooks/provider for entityFields

THIRD-PARTY-NOTICES, src/components/Editor.tsx
Even though all dependent fields are set, puckInitialHistory doesn't always get set in time before the editor loads, making it crash. This adds even more guarding. I was seeing this in local dev.
=> fix: puckInitialHistory not set in time

src/internal/puck/components/Header.tsx
The entity fields toggle was switching off when the page saved because it was not passing the toggle state to the component.
=> fix: entity fields toggle incorrectly switching off

src/components/EntityField.tsx
When EntityField (which uses Tooltip under the hood) wraps an Accordion, it results in all content that occurs afterward to be duplicated in the DOM. Setting `asChild` to the TooltipTrigger fixes it.
https://github.com/radix-ui/primitives/discussions/560#discussioncomment-5325935
=> fix: accordions inside EntityField tooltip

THIRD-PARTY-NOTICES, pnpm-lock.yaml, src/components/README.md, src/utils/getFilteredEntityFields.ts, src/utils/renderEntityFields.tsx
- makes filter required
- makes filter.types required
- eliminates filter.allowSubfields (now always true)
- fixes children of list types showing up
- fixes parents of subfields not being included
- runs the allowList/disallowList after walking subfields
- allowList and disallowList are now text matches on the full field name
For example, if you have `c_hero.cta1`, `c_hero.cta2`, and `c_promo.cta`:
```
filter: {
types: ["c_cta"],
disallowList: ["c_hero.cta1"]
} =>  [c_hero.cta2, c_promo.cta]
filter: {
types: ["c_cta"],
disallowList: ["c_hero"]
} =>  [c_promo.cta]
filter: {
types: ["c_cta"],
disallowList: ["promo"]
} =>  [c_hero.cta1, c_hero.cta2]
```
=> fix: mappable fields filter updates

src/components/YextEntityFieldSelector.tsx, src/utils/getFilteredEntityFields.ts
Only display the Static Value field if it's type.string or type.phone. Probably more basic types to do this for in the future.
=> feat: hide static value field for complex entity types

src/hooks/useEntityFields.tsx, src/internal/types/entityFields.ts, src/utils/getFilteredEntityFields.test.ts, src/utils/getFilteredEntityFields.ts
This uses the local stream definition for a template to determine the list of mappable entity fields while in dev mode.
TEST=manual
I used a local build of `visual-editor` to run the starter locally and confirmed that the entity fields in dev mode were based on the local stream definition.
=> feat(util): use local stream for entity fields in dev mode

src/internal/components/InternalEditor.tsx
There's no way to get rid of the sidebar section titles via individual component puck overrides.
We could override the entire Puck component, but most of the default Puck components are not exported so we'd have to fork a number of files from Puck into our package and maintain them in parallel.
This solution grabs entire ComponentList from the left side bar and the title from the right side bar and hides them via the DOM.
=> fix: hide sidebar titles in theme mode via DOM

src/internal/components/InternalEditor.tsx, src/internal/puck/components/Header.tsx
We were using InitialPuckHistory which does not update to reset the local changes.
We also were not updating the history after clearing local changes.
After these changes, history is updated and clear local changes is disabled after publish.
After publish, user can add and clear local changes as expected.
=> fix(components): fixed history desync after publish

src/internal/components/InternalEditor.tsx, src/internal/puck/components/Header.tsx, src/internal/types/templateMetadata.ts
This removed the theme mode toggle from the header and uses `templateMetadata.isThemeMode` to determine if the editor is in theme mode.
=> feat: remove theme mode toggle

src/components/Editor.tsx, src/internal/components/InternalEditor.tsx, src/internal/puck/components/ThemeSidebar.tsx, src/utils/applyTheme.ts, src/utils/devLogger.ts
- uses MutationObserver api to update styles
- moves all console logs to devLogger (should work with Brian's query params changes)
- removes puckRendered since we did not end up using it
=> chore: clean up theme manager

src/components/Editor.tsx, src/internal/components/InternalEditor.tsx, src/internal/puck/components/ThemeSidebar.tsx
Adds theme preview for dev mode.
- Also fixes preview for VE in dev mode for the initial load. It was only working after a change was made.
- Now only pulls the published VE data for theme mode
- Properly clears history between theme and VE
=> feat: add dev mode theme preview

THIRD-PARTY-NOTICES, src/components/Editor.tsx, src/internal/components/LayoutEditor.tsx, src/internal/components/ThemeEditor.tsx, src/internal/hooks/layout/useMessageReceivers.ts, src/internal/hooks/theme/useMessageReceivers.ts, src/internal/hooks/useMessageReceivers.ts
- creates useCommonMessageReceivers, useLayoutMessageReceivers, useThemeMessageReceivers
- Editor.tsx now calls iFrameLoaded and receives puckConfig, templateMetadata, document, and visualConfigurationData
- Then, either LayoutEditor or ThemeEditor is loaded, iFrameLoaded is called again, and the subeditors receive layoutSaveState or themeData+themeSaveState 
Together with https://gerrit.yext.com/c/alpha/+/273121
=> refactor: separate message receivers

src/utils/applyTheme.test.ts, src/utils/applyTheme.ts
Switches from using outerHTML to using innerText for the in-editor theme updating. Should be safer against XSS
=> fix: remove outerHTML vulnerability 

src/internal/puck/components/ThemeSidebar.tsx, src/internal/puck/ui/puck.css
AutoFieldPrivate will be removed in a future version of Puck as it was never supposed to be exported.
=> refactor: switch <AutoFieldPrivate> to <AutoField> 

src/internal/components/ThemeEditor.tsx
On layout switch, I think there was a race condition that if templateMetadata was sent faster than themeData, then loadPuckInitialHistory would run but still have the old data and so it wouldn't update the preview
=> fix: preview doesn't update on layout switch

src/components/puck/Image.tsx
Verified that the label appears correctly and the component name shows up as "Image" instead of "ImageWrapperComponent"
=> fix: add label to ImageWrapperComponent

src/internal/utils/getFilteredEntityFields.ts
This updates `getFilteredEntityFields` to accept a new `includeListsOnly` field in the filter. When this field is not provided or set to `false`, the behavior is the same as before, and list fields are filtered out. If it is set to `true`, then list fields are returned and non-list fields are filtered out.
=> feat: update getFilteredEntityFields to return lists

src/hooks/useEntityFields.tsx
Fixes the problem where the schemaFields in devMode were not formatted correctly and thus not always showing up as options in the EntityFieldSelector
=> fix: formatting of entity fields when used in devMode 

src/components/editor/EntityField.tsx
Even when the Entity Field tooltips were closed, they were adding extra divs to the page. These could get in the way of styling, such as this set of buttons that were supposed to be `width: 100%, flexWrap: "wrap"`
Before:
After:
=> fix: entity field tooltips mess up css layout

src/components/editor/Editor.tsx, src/internal/components/InternalLayoutEditor.tsx, src/internal/components/LayoutEditor.tsx, src/internal/components/ThemeEditor.tsx, src/internal/hooks/layout/useMessageReceivers.ts, src/internal/hooks/theme/useMessageReceivers.ts, src/internal/hooks/useMessageReceivers.ts, src/internal/puck/components/LayoutHeader.tsx, src/internal/types/saveState.ts
This adds types to the layout data so it's much easier to work with. Additionally, convert the types as soon as they are received in the messageReceivers instead of doing it in multiple places downstream.
=> refactor: type layout data

src/internal/components/InternalThemeEditor.tsx, src/internal/components/ThemeEditor.tsx, src/internal/puck/components/ThemeHeader.tsx, src/internal/puck/components/ThemeSidebar.tsx, src/internal/utils/constructThemePuckFields.test.ts, src/internal/utils/constructThemePuckFields.ts, src/internal/utils/internalThemeResolver.test.ts, src/internal/utils/internalThemeResolver.ts, src/utils/README.md, src/utils/applyTheme.test.ts, src/utils/applyTheme.ts, src/utils/themeResolver.test.ts, src/utils/themeResolver.ts
- allows the top level keys of theme.config to be any string -> allows custom organization in the TM UI
- reshapes the theme.config when dumping into tailwind.config, organized by the plugin value 
- no longer allows unlimited depth style objects, each section of the theme.config can only have direct child styles or one-deep StyleGroups if that group shares the same plugin
- classes created follow the format `[tailwindUtility]-[sectionName]-[styleName]-[subStyleName?]`
- css variables created follow the format `--[pluginName]-[sectionName]-[styleName]-[subStyleName?]`
Starter repo PR that uses this: https://github.com/YextSolutions/pages-visual-editor-starter/pull/159
=> refactor: new theme.config format

THIRD-PARTY-NOTICES, src/components/puck/GridSection.tsx, src/components/puck/HoursStatus.tsx
- fixes changes to horizontalSpacing not being reflected by GridSection
- adds back showDayNames and dayOfWeekFormat to HoursStatus, which I temporarily removed because the underlying prop type from pages-components had changed
=> fix: props QA for GridSection and HoursStatus

src/components/editor/Editor.tsx, src/internal/components/LayoutEditor.tsx, src/internal/hooks/theme/useLocalStorage.ts, src/internal/hooks/useMessageReceivers.ts
If themeId is not present, it will simply not try to apply the theme from local storage.
=> fix: layout editor no longer requires themeId

src/components/puck/Address.tsx, src/components/puck/CtaWrapper.tsx, src/components/puck/Emails.tsx, src/components/puck/FlexContainer.tsx, src/components/puck/GetDirections.tsx, src/components/puck/GridSection.tsx, src/components/puck/HeadingText.tsx, src/components/puck/HoursCard.tsx, src/components/puck/HoursStatus.tsx, src/components/puck/Image.tsx, src/components/puck/Phone.tsx, src/components/puck/TextList.tsx, src/components/puck/assets/svg.d.ts, src/components/puck/atoms/button.tsx, src/components/puck/atoms/cta.tsx, src/components/puck/atoms/section.tsx, src/components/puck/registry/components.ts, src/internal/components/atoms/Alert.tsx, src/internal/components/atoms/Button.tsx, src/internal/puck/ui/AlertDialog.tsx, src/internal/puck/ui/Progress.tsx, src/internal/puck/ui/Tooltip.tsx, src/internal/puck/ui/button.tsx, src/internal/puck/ui/label.tsx, src/internal/puck/ui/radio.tsx, src/internal/puck/ui/switch.tsx, src/utils/index.ts, src/utils/yextCn.ts
- updates all component imports to work in the starter too
- exports our local `cn` utility as `yextCn` so that it works in the components
=> feat: add all components to registry

src/components/index.ts, src/components/puck/Address.tsx, src/index.ts
The components were exported before their dependencies, which caused vite to throw an error in the starter.
Also removed `typeof config` from Address.tsx, which was a bad autocompleted import.
=> fix: cannot access before initialization error

src/components/puck/HoursCard.tsx, src/components/puck/HoursStatus.tsx
Uses an entityField for hours
Also changes any -> HoursType in the YextEntityFieldSelector
Ran npx prettier on HoursStatus and HoursCard
=> feat: hoursCard uses hours entity field

src/utils/resolveYextEntityField.ts
If no entity field is selected or constantValueEnabled is true, then use the constant value.
Tested on dev account.
=> fix: use constantValue if no entity field is selected

src/components/editor/YextEntityFieldSelector.tsx
Hides the constant value option if we don't have a configuration for it defined.
For hours, we specifically do not want to allow constant values.
Verified that constant value can be chosen for expected types, but not for hours.
=> fix: hide constant value option if not defined

src/components/puck/HoursTable.tsx, src/components/puck/index.ts
This aligns better with the PagesComponent underlying component
Requested by Aaron
=> fix: rename HoursCard to HoursTable

src/internal/components/atoms/Alert.tsx, src/internal/puck/ui/puck.css
Doesn't solve the core problem that the theme sidebar is Frankensteined but does fix the padding inconsistencies
=> fix: make theme sidebar padding more consistent

src/components/puck/GridSection.tsx, src/components/puck/atoms/section.tsx
Talked with aaron and decided to remove vertical spacing as it isn't viewable while editing. Also made padding happen to the entire grid component (not per grid item). 
I know it's ugly to have all the padding classes in a giant object, but tailwind wouldn't recognize
`const paddingClasses = [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24].map(n => ({label: ${n}, value: py-${n}}))`
as non-dynamic tailwind classes...
Tested in local dev and made sure all the paddings worked as expected
=> fix: adjust Grid components padding 

src/internal/components/LayoutEditor.tsx, src/internal/components/ThemeEditor.tsx, src/internal/hooks/layout/useMessageSenders.ts, src/internal/hooks/theme/useMessageSenders.ts, src/internal/hooks/useMessageSenders.ts
We're now sharing the local save state between theme and layout dev mode, but dev previews were not set up to receive both so the generated preview did not match the iframe preview.
Together with https://gerrit.yext.com/c/alpha/+/276311
=> fix: dev mode previews don't match puck iframe

src/internal/hooks/layout/useMessageReceivers.ts, src/internal/hooks/theme/useMessageReceivers.ts, src/utils/devLogger.ts
The new data structure is that the save state always exists for a layout, but the history is null/"" if we should just be using the published data.
Also standardizes the theme/layout save state receivers.
=> refactor: update save state receivers

src/components/editor/Editor.tsx, src/internal/components/InternalLayoutEditor.tsx, src/internal/components/InternalThemeEditor.tsx, src/internal/components/LayoutEditor.tsx, src/internal/components/ThemeEditor.tsx, src/internal/hooks/layout/useMessageSenders.ts, src/internal/hooks/theme/useMessageSenders.ts, src/internal/hooks/useMessageReceivers.ts, src/internal/hooks/useMessageSenders.ts, src/utils/devLogger.ts
While we are doing breaking changes, we might as well update the message names that were created pre-themes, which can be confusing.
https://gerrit.yext.com/c/alpha/+/278839
=> refactor: rename messengers

src/components/puck/Header.tsx, src/components/puck/index.ts, src/components/puck/registry/components.ts
Unfortunately have to do some id mess so that the links don't duplicate when you add/edit the array field
See the puck demo for ArrayFields: https://github.com/measuredco/puck/blob/main/apps/demo/config/blocks/Columns/index.tsx
=> feat: add header component

src/internal/puck/components/FontSelector.tsx, src/internal/utils/constructThemePuckFields.test.ts, src/internal/utils/constructThemePuckFields.ts
Upcoming puck fixes make the font selector re-mount more, so we need to use useCallback (like we do for the entire ThemeSidebar)
This works with our current puck version, but isn't needed until we upgrade again
=> fix: font selector does not work with recent puck canaries

src/components/puck/Card.tsx, src/components/puck/index.ts, src/components/puck/registry/components.ts
Adds the card component from the visual-editor starter
Uses the atomic components Header, Body, Image, and CTA for all fields
Tested on dev account
=> feat: add card component

src/components/puck/Header.tsx, src/internal/utils/getFilteredEntityFields.ts
Calling uuid at build time was causing an error, this only uses uuid at runtime and has better handling of link duplication.
=> fix: header links fail build

src/components/puck/Footer.tsx, src/components/puck/Header.tsx
The link must be defined or the component crashes.
Also updated the analytics event name to be more specific.
=> fix: undefined header and footer links

src/components/editor/EntityField.tsx, src/components/puck/Address.tsx, src/components/puck/BodyText.tsx, src/components/puck/Card.tsx, src/components/puck/CtaWrapper.tsx, src/components/puck/Emails.tsx, src/components/puck/HeadingText.tsx, src/components/puck/HoursStatus.tsx, src/components/puck/HoursTable.tsx, src/components/puck/Image.tsx, src/components/puck/Phone.tsx, src/components/puck/Promo.tsx, src/components/puck/TextList.tsx
On empty entityField, keep tooltip
On constant, don't show any tooltip. 
Within Card component, when EntityField is toggled, no changes to sizing
=> fix: entityField Wrapper

src/internal/hooks/theme/useMessageReceivers.ts
themeSaveState from alpha was formatted a bit differently. Fixed it so themeSaveState works and now after "publish" the theme is correct (even when u switch entities)
=> fix: themeSaveState didn't match data from messenger

src/components/puck/Emails.tsx
This sets the `emails` field as the default entity field for the Emails component.
=> feat: set default field for emails component

src/components/puck/Card.tsx, src/components/puck/Promo.tsx, src/components/puck/atoms/button.tsx
For buttons, which are used in cta and
Get Directions, selecting a font-size larger than 5xl would make the text bleed out of the button.
This change removes the font size options larger than 4xl per Aaron's request.
=> fix: limit font-size for buttons

src/components/editor/YextEntityFieldSelector.tsx, src/internal/puck/constant-value-fields/ConstantField.tsx, src/internal/puck/constant-value-fields/Phone.tsx, src/internal/puck/constant-value-fields/Text.tsx
Fixes a bug I introduced in #193 
Was trying to use the custom ConstantField styling for all constant value inputs, but missed that the ConstantField function depended on the the field being an object type. This PR reverts Phone and Text to being text types but adds a case to render a styled FieldLabel for them.
=> fix: error in constant text fields

src/utils/visualEditorFonts.ts
getFontWeightOverrideOptions is set up to wait for the DOM to mutate before getting the theme data because puck runs resolveFields before the document is fully loaded.
However, if getFontWeightOverrideOptions is used in a manually-defined resolveFields function (like I added in footer), resolveFields hangs because the DOM doesn't mutate further. This results in the sidebar being stuck in a loading state.
This PR updates getFontWeightOverrideOptions to try to get the theme data when it is called and then start the MutationObserver if it cannot be found.
=> fix: resolveData stuck when updating footer props

src/internal/puck/constant-value-fields/TextList.tsx
Fixes a bug where pressing enter in a text list would sometimes remove the item. Instead, pressing enter always adds a new item and focuses it.
The underlying problem here is that using Puck's AutoField/IconButton like this limits our access to the underlying html elements (AutoField/IconButton are exported from Puck but don't have complete APIs), which makes this controlling complex behavior trickier.
=> feat: pressing enter creates new item in list

THIRD-PARTY-NOTICES, package.json, pnpm-lock.yaml
https://github.com/measuredco/puck/compare/v0.17.0...v0.17.4
I think https://github.com/measuredco/puck/commit/e778246e4ae8925f3d04962369a33a9c1a4b6589 means we don't have to do as many null checks as we do in the components, but they won't hurt
=> chore: upgrade puck to 0.17.4

THIRD-PARTY-NOTICES, package.json, pnpm-lock.yaml, src/components/editor/Editor.tsx, src/internal/hooks/useMessageSenders.ts
Capture errors in the editor and send to parent
Receiver in YSS coming soon but I wanted to get this in before we do a release
I have the fallback just set to <></> because I was presuming we'd want a mana ui error state which needs to be rendered by the parent
=> feat: set up error boundary and send errors to parent

packages/visual-editor/src/components/editor/Editor.tsx
window.location.ancestorOrigins is not a property in Firefox (might be someday but is currently held up in security discussions)
We can use document.referrer instead with a small iframe policy change in storm.
=> fix: editor does not load in firefox

packages/visual-editor/src/components/puck/GetDirections.tsx
Now the Get Direction component's link opens in a new tab. This matches how the address component's link already worked.
=> fix: links open in new tab

packages/visual-editor/src/utils/README.md, packages/visual-editor/src/utils/applyAnalytics.ts, packages/visual-editor/src/utils/index.ts
Returns a Google Tag Manager script that uses the Google Tag Manager ID set in the Theme Editor
=> feat: add applyAnalytics

packages/visual-editor/src/components/editor/BorderRadiusSelector.tsx, packages/visual-editor/src/components/editor/FontSizeSelector.tsx, packages/visual-editor/src/components/puck/CtaWrapper.tsx, packages/visual-editor/src/components/puck/GetDirections.tsx, packages/visual-editor/src/utils/README.md, packages/visual-editor/src/utils/themeConfigOptions.ts, starter/theme.config.ts
fixed it so that 5xl, 6xl, 7xl... doesn't show up anymore. There's a separate CR to update the starter's theme.config
=> fix: update button font size options

packages/visual-editor/package.json, packages/visual-editor/src/components/puck/Phone.tsx, pnpm-lock.yaml
This change makes the Phone component correctly format phone numbers based on the country code. This uses the `libphonenumber-js` library to automatically parse the phone number and then format it in either the domestic or international format. Tested locally and ensured that phone numbers with various country codes were formatted as expected.
=> fix: format phone numbers correctly

packages/visual-editor/src/components/editor/EntityField.tsx
This memoizes the children that are passed into the entity field tooltip so that they do not re-render when the entity field tooltip toggle is enabled or disabled.
I tested the change locally and confirmed that nothing re-renders, and the tooltips are cleanly added and removed as expected.
=> fix: prevent re-renders on entity field tooltip toggle

.github/workflows/semgrep_check.yml
Ubuntu 20.04 for Github Actions is being deprecated and will be fully unsupported on 2025-04-01. Update our semgrep action to the latest version.
=> chore: update semgrep_check.yml to use ubuntu-latest

packages/visual-editor/src/internal/components/InternalThemeEditor.tsx, packages/visual-editor/src/internal/puck/components/ThemeHeader.tsx
This adds undo and redo buttons to theme manager. Confirmed locally that the undo and redo buttons work as expected; they are disabled when there is nothing to go back to or go forward to, and they correctly update the index of the theme history. Making an edit while there are changes to "redo" erases those changes and moves the index to the end of the history with the new edit.
=> feat: add undo/redo buttons to theme manager

packages/visual-editor/src/internal/components/InternalLayoutEditor.tsx
I'm not really sure why this fixes the flickering but it does. The problem seemed tied to layoutSaveState finishing and the config shouldn't be related, but Puck's rendering is often a little weird
Non-flickering example: https://www.yext.com/s/4259018/yextsites/153063/editor#pagesetId=newloc5&layoutId=newloc5-default-layout&themeId=ve-5&entityId=1095527880
=> fix: editor flickers when saving state

packages/visual-editor/src/components/editor/Editor.tsx, packages/visual-editor/src/hooks/useEntityFields.tsx, packages/visual-editor/src/internal/utils/getFilteredEntityFields.ts, packages/visual-editor/src/utils/VisualEditorProvider.tsx
usePlatformBridgeEntityFields was undefined until the platform sent down the stream information, which would occasionally happen after all the other data was sent down. The other data was checked before loading the editor but this wasn't because it's set as context outside of the normal loading flow. `useEntityFields must be used within VisualEditorProvider` was thrown when the entityFields are undefined and useEntityFields is called, which is now immediately after loading because we render a YextEntityField selector for the root fields.
This fix distinguishes between not-in-provider and no-loaded-yet and checks that entity fields have loaded before loading the editor
=> fix: useEntityFields must be used within VisualEditorProvider

packages/visual-editor/src/components/puck/Grid.tsx
Fixed Grid columns so on mobile there's only one column. Confirmed theme padding works as expected.
=> fix: grid columns on mobile

packages/visual-editor/src/components/puck/Address.tsx, packages/visual-editor/src/components/puck/Card.tsx, packages/visual-editor/src/components/puck/CtaWrapper.tsx, packages/visual-editor/src/components/puck/GetDirections.tsx, packages/visual-editor/src/components/puck/Promo.tsx, packages/visual-editor/src/components/puck/atoms/cta.tsx, starter/src/ve.config.tsx
Updates GetDirections to use CTA instead of a Button + Link combo.
Updates various other components to add a Link Type prop or set one by default.
Fixes a VE crash when entering a blank constant value for Promo or Card CTA link.
Verified that the appearance and functionality of the components are not any different than before.
=> refactor: update components to use Link

packages/visual-editor/src/components/puck/Phone.tsx
Adds an option to include a hyperlink for the phone component.
The option is similar to what is available in the Emails component.
When a hyperlink is included, an underline is added to the phone that disappears on hover.
=> feat: add includeHyperlink option to Phone component

packages/visual-editor/package.json, packages/visual-editor/src/components/editor/Editor.tsx, packages/visual-editor/src/internal/components/LayoutEditor.tsx, packages/visual-editor/src/internal/components/ThemeEditor.tsx, packages/visual-editor/src/internal/hooks/useProgress.test.ts, packages/visual-editor/src/internal/hooks/useProgress.ts, packages/visual-editor/src/internal/puck/components/LoadingScreen.tsx, pnpm-lock.yaml
This fixes an issue that caused the progress bar to go backwards at times. It also adds a new `useProgress` hook that provides `isLoading` and `progress` values when given a set of completion criteria so we can more easily work with the progress bars in the future.
https://github.com/user-attachments/assets/4daf5508-d844-4d31-9c12-eb096bf4f879
=> fix: prevent loading bar from going backwards

packages/visual-editor/src/components/puck/Footer.tsx
Links that didn't have a prefix were showing up as `undefinedhttps:// ...`
=> fix: undefined footer links

packages/visual-editor/src/internal/puck/components/ThemeHeader.tsx
This switches Puck to interactive mode so the overlays go away but then adds a click listener to the iframe so that button/link clicks don't bomb out the editor.
https://github.com/user-attachments/assets/5b931e38-e316-43c8-a5b1-cefb0afc14e4
=> feat: disable component selection in theme mode

packages/visual-editor/src/components/editor/Editor.tsx
Resellers can serve Storm from a white labelled url other than yext.com, so we can't do a simple referrer url check.
This checks if the editor has been loaded in any iframe -- while this is more permissive than the old check, I think the main point is to ensure hitting /edit directly from a browser/crawler returns a 404?
=> fix: editor returns error 404 when in reseller account

packages/visual-editor/src/utils/applyAnalytics.ts
To be tested when the VE siteSettings PRs are merged
=> feat: get googleTagManagerId from visualEditorConfig instead of theme

packages/visual-editor/src/components/puck/Breadcrumbs.tsx, packages/visual-editor/src/components/puck/Directory.tsx
relativePrefixToRoot is a property of TemplateProps instead of document
Consulting also has a sneaky addition of the current entity to the breadcrumbs [here](https://github.com/yextconsulting/pages-starter-react-consulting/blob/main/src/layouts/region/transformProps.tsx) that we were missing 
If directory parents come back without name fields, filter those items out so that undefined does not appear
=> fix: read relativePrefixToRoot from templateProps

packages/visual-editor/src/vite-plugin/plugin.ts
So without these changes, buildStart would occur multiple times (likely due to our vite server start up via express). Changed it to only generateFiles once on server start. 
Past thread: https://github.com/yext/visual-editor/pull/252#discussion_r1993933560
=> fix: adjust plugin on server start

packages/visual-editor/src/utils/applyAnalytics.ts
The field is directly on visualEditorConfig rather than under siteAttributes like it was for theme
=> fix: google tag manager id path

packages/visual-editor/src/components/editor/BasicSelector.tsx, packages/visual-editor/src/components/puck/HeadingText.tsx, packages/visual-editor/src/components/puck/atoms/heading.tsx
This replaces the number input for heading text level with a combobox selector. It also makes the heading use styling for the level below the selected one when viewed on mobile.
=> feat: use selector for heading text level

packages/visual-editor/src/components/puck/Emails.tsx
This removes the styling fields/props from the Emails component and fixes an issue with empty constant text fields and links.
=> feat: emails component updates

packages/visual-editor/src/components/puck/Footer.tsx, packages/visual-editor/src/components/puck/Header.tsx, packages/visual-editor/src/utils/README.md, packages/visual-editor/src/utils/index.ts, packages/visual-editor/src/utils/themeConfigOptions.ts, starter/tailwind.config.ts
- Creates the tailwind colors based on the theme editor colors
- palette-primary-light
- palette-secondary-light
- palette-tertiary-light
- palette-quaternary-light
- palette-primary-dark
- palette-secondary-dark 
- Overrides tailwind's grays with the 9 grays from the Figma 
- Creates a helper to provide the 7 background options
- Updates header to always use the white background and footer to have the 7 background options
=> feat: autogenerated theme colors

packages/visual-editor/src/components/puck/CtaWrapper.tsx, packages/visual-editor/src/components/puck/atoms/button.tsx, packages/visual-editor/src/components/puck/atoms/cta.tsx
This removes styling options from CtaWrapper and adds a "secondary" button option. This will need to be updated later with the secondary styling settings from the theme.
=> feat: cta component updates

packages/visual-editor/package.json, packages/visual-editor/src/components/editor/BasicSelector.tsx, packages/visual-editor/src/components/puck/TextList.tsx, packages/visual-editor/src/internal/puck/ui/Combobox.tsx, pnpm-lock.yaml
cmdk's CommandItem component expects all values to be strings, and produces inconsistent results when non-string values are provided. We want our BasicSelector to work for non-string values like numbers (such as in the HeadingText component's level field), so this change stringifies the values that are passed in, and updates BasicComponent to select the option with the value that, when stringified, matches the value that was clicked. This also updates the cmdk package to ensure we get other bug fixes that have been released (although the newest version still does not handle non-string values).
Tested manually and confirmed that BasicSelector works as expected for both string and non-string values.
=> fix: handle non-string values correctly in BasicSelector

packages/visual-editor/src/components/editor/BorderRadiusSelector.tsx, packages/visual-editor/src/components/puck/Banner.tsx, packages/visual-editor/src/components/puck/Breadcrumbs.tsx, packages/visual-editor/src/components/puck/Card.tsx, packages/visual-editor/src/components/puck/Directory.tsx, packages/visual-editor/src/components/puck/Emails.tsx, packages/visual-editor/src/components/puck/Flex.tsx, packages/visual-editor/src/components/puck/Footer.tsx, packages/visual-editor/src/components/puck/Grid.tsx, packages/visual-editor/src/components/puck/HoursTable.tsx, packages/visual-editor/src/components/puck/Layout.tsx, packages/visual-editor/src/components/puck/Phone.tsx, packages/visual-editor/src/components/puck/Promo.tsx, packages/visual-editor/src/components/puck/TextList.tsx, packages/visual-editor/src/components/puck/atoms/body.tsx, packages/visual-editor/src/components/puck/atoms/heading.tsx, packages/visual-editor/src/components/puck/atoms/section.tsx
Uses the new background styles for all background and text color
In general, removes text color as a class that is set in individual components, so that the text color set by the Grid/Flex/Section is inherited.
CTAs still need to be updated to the new styles, so they are a little off.
https://github.com/user-attachments/assets/f3b2b655-1927-47b1-95c1-bb828b9f0661
=> refactor: update text and background color for components

starter/src/components/Locator.tsx, starter/src/templates/dev.tsx
This PR adds basic result cards, still in need of styling. It also
adjusts how the SearchHeadlessProvider is created, so that the
call to provideHeadless is not inside of a component. This may need
adjusting.
J=WAT-4699
TEST=manual
Results are populated, albeit unstyled. No rerendering issues
=> feat: add basic result cards

packages/visual-editor/src/components/editor/SpacingSelector.tsx, packages/visual-editor/src/components/puck/Directory.tsx, packages/visual-editor/src/components/puck/Flex.tsx, packages/visual-editor/src/components/puck/Grid.tsx, packages/visual-editor/src/components/puck/Layout.tsx, starter/theme.config.ts
This removes the Maximum Content Width option from the Grid component, and simplifies the behavior of columns. The column field is now a basic number field, and columns wrap to rows on small screen sizes if the Grid is at the top level of the layout, but are fixed to a horizontal alignment at all times if the Grid is at a lower level. This also renames the padding fields and shows the raw px values for spacing rather than the more complicated "[number] ([pixel_value]px)" format.
This screenshot shows two Grids containing CTA buttons on a small mobile screen. The top grid is at the top level of the layout, so it wraps into one column with multiple rows. The bottom grid is within another grid, so the buttons are always horizontally aligned into columns.
=> feat: update grid component

packages/visual-editor/src/utils/applyTheme.test.ts, packages/visual-editor/src/utils/applyTheme.ts, packages/visual-editor/src/utils/colors.test.ts, packages/visual-editor/src/utils/colors.ts, packages/visual-editor/src/utils/index.ts, packages/visual-editor/src/utils/themeConfigOptions.ts, starter/theme.config.ts
- Adds a few utilities in `packages/visual-editor/src/utils/colors.ts` to support checking color contrast
- Automatically adds either black or white as a contrasting color for each of the 4 colors in the palette
- Updates the theme.config with new fields for Link and Button
=> refactor: theme and utility updates to support updated link and button styles

packages/visual-editor/src/components/puck/Address.tsx, packages/visual-editor/src/components/puck/BodyText.tsx, packages/visual-editor/src/components/puck/Breadcrumbs.tsx, packages/visual-editor/src/components/puck/Card.tsx, packages/visual-editor/src/components/puck/Directory.tsx, packages/visual-editor/src/components/puck/Emails.tsx, packages/visual-editor/src/components/puck/Footer.tsx, packages/visual-editor/src/components/puck/HoursStatus.tsx, packages/visual-editor/src/components/puck/HoursTable.tsx, packages/visual-editor/src/components/puck/Promo.tsx, packages/visual-editor/src/components/puck/atoms/body.tsx, packages/visual-editor/src/components/puck/atoms/button.tsx, packages/visual-editor/src/utils/themeConfigOptions.ts, starter/theme.config.ts
- Creates `text-body-sm-fontSize` and `text-body-lg-fontSize` classes based on the body font size set in theme editor.
- Updates the Body atom to use the Variant option (small, base, large)
- Updates components that use body text to use the variant in the Figma
- Drops link fontSize
=> refactor: body theme updates

starter/src/components/Locator.tsx, starter/src/templates/dev.tsx
This PR adds a little more styling to the result cards.
It also builds out a variety of information, including:
- name
- address
- basic hours
- distance
- phone number
- slug link
- map link
Some changes will follow - the hours display will use a
forthcoming display util to be added to search-ui-react, and
a later change will pass down styling from the VLE in general
J=WAT-4699
TEST=manual
=> feat: add additional result card data, and basic styling

starter/src/ve.config.tsx
- adds categories to the sidebar (any item not in a category will be in "other"
- disallows using content blocks at the root level
=> feat: add categories to the components list

packages/visual-editor/src/components/puck/Card.tsx, packages/visual-editor/src/components/puck/Directory.tsx, packages/visual-editor/src/components/puck/Flex.tsx, packages/visual-editor/src/components/puck/Footer.tsx, packages/visual-editor/src/components/puck/Grid.tsx, packages/visual-editor/src/components/puck/HeadingText.tsx, packages/visual-editor/src/components/puck/Promo.tsx, packages/visual-editor/src/components/puck/atoms/heading.tsx, packages/visual-editor/src/components/puck/atoms/section.tsx, packages/visual-editor/src/utils/README.md, packages/visual-editor/src/utils/index.ts, packages/visual-editor/src/utils/themeConfigOptions.ts
Moves `headingLevelOptions` to themeConfigOptions.tsx for export from the package
Also updates a number of imports that should have been importing through the package alias rather than specific files
=> fix: export heading options

packages/visual-editor/src/components/puck/Card.tsx, packages/visual-editor/src/components/puck/Image.tsx, packages/visual-editor/src/components/puck/Promo.tsx, packages/visual-editor/src/components/puck/atoms/image.tsx, packages/visual-editor/src/components/puck/atoms/index.ts, packages/visual-editor/src/components/puck/index.ts, packages/visual-editor/src/components/puck/registry/components.ts, packages/visual-editor/src/internal/puck/constant-value-fields/Image.tsx
Added an image atom to be used in other components. 
If `auto` -> fills entire container matching aspectRatio
if `fixed` -> user can set the width and height
Video of how excessively large fixed width is handled
https://github.com/user-attachments/assets/53285f5a-12a9-4cbf-83b4-df9609b4656a
=> refactor: image, promo, card

packages/visual-editor/src/components/puck/Card.tsx, packages/visual-editor/src/components/puck/Promo.tsx, packages/visual-editor/src/components/puck/index.ts
Was getting `[vite:css] [postcss] Cannot access 'Ur' before initialization` -- `Ur` is the minified name of `ImageWrapperFields`
I suggested to move the ImageWrapper imports to be from the package in #300 but that was a bad suggestion. Basically, you can't do `../../index.js` imports if the object you are importing is exported at the same level as the file that is importing it. The declaration is hoisted but it's not been initialized yet.
I think we can just do the direct import for now since we're probably adding a YextField helper soon
=> fix: image import build error

packages/visual-editor/src/components/editor/EntityField.test.tsx, packages/visual-editor/src/components/editor/EntityField.tsx, packages/visual-editor/src/components/puck/Footer.tsx, packages/visual-editor/src/components/puck/atoms/button.tsx, packages/visual-editor/src/internal/components/InternalLayoutEditor.tsx, packages/visual-editor/src/internal/components/InternalThemeEditor.tsx, packages/visual-editor/src/internal/puck/ui/EntityFieldsToggle.tsx
Entity Field Tooltips
- rename `useEntityField` => `useEntityTooltips` because we also have `useEntityFields`
- if `useEntityTooltips` is undefined (because it is being called on the actual page, not the editor), return children directly rather than adding wrapping divs
- Set the tooltip div to be `width: fit-content` so the outline boxes match the underlying component
Footer
- Add padding to links to match Figma
CTAs/Buttons
- fix issue where background isn't updated when switched from Primary to Secondary
- eliminate unnecessary color transition
=> fix: miscellaneous component updates

packages/visual-editor/src/components/editor/BasicSelector.tsx
shadcn's combobox component searches by value, but the values we pass in are often completely different from the labels that the user sees. This change passes the options from the BasicSelector into the combobox with the values set to match the labels, since the combobox component doesn't need to know what the actual values are. This way, the combobox searches by the values, it's really searching by labels, which is more intuitive for the user. 
Verified that the search functionality on the BasicSelector works for options with strings, numbers, or objects as values, and it still correctly selects options as expected.
https://github.com/user-attachments/assets/995bf259-a150-42da-bb76-196db2ea152e
=> fix: search combobox options by label

packages/visual-editor/src/components/editor/EntityField.tsx, packages/visual-editor/src/components/puck/Footer.tsx
- the footer padding should not apply on mobile
- the w-fit for the entity field wrapper was causing issue with w-full for CTAs. While this change makes the Entity Field tooltip outline larger than it should be, it's a better UX because the editor's layout matches the live page layout for mobile
=> fix: mobile footer and entity field wrapper

starter/src/components/Locator.tsx
This PR performs the following changes to bring the locator in line with mocks:
- Adds text for before a search is performed
- Adjusts more elements (map search button, no result text) to change dynamically
- Adds result count above result output
- removes unused styling props
=> feat: non-result card locator mock styling, and cleanup

packages/visual-editor/src/components/editor/YextEntityFieldSelector.tsx
Since we added the entity field selector, clicking the labels of the radio toggle didn't work in array fields for some reason, which has become more relevant for the page section components that have an array of cards
=> fix: radio toggle label doesn't work in array fields

packages/visual-editor/src/components/puck/NearbyLocations.tsx, packages/visual-editor/src/components/puck/Phone.tsx, packages/visual-editor/src/components/puck/atoms/index.ts, packages/visual-editor/src/components/puck/atoms/phone.tsx, packages/visual-editor/src/components/puck/index.ts, starter/src/ve.config.tsx
Renames the phone atom to "PhoneAtom"
Changes the name of the Phone component back from "PhoneWrapper" to "Phone"
This prevents breaking sites with a ve.config.ts that had the original "Phone" component
=> fix: rename phone atom and wrapper

packages/visual-editor/src/components/editor/YextEntityFieldSelector.tsx, packages/visual-editor/src/components/puck/Address.tsx, packages/visual-editor/src/components/puck/registry/components.ts, packages/visual-editor/src/internal/utils/getFilteredEntityFields.test.ts, packages/visual-editor/src/internal/utils/getFilteredEntityFields.ts
Fixes the React hook inside a hook warning by moving the useContext outside of the useMemo
Fixes the valid DOM nesting because Address was inside a `<p>`
=> fix: console warnings

packages/visual-editor/src/internal/hooks/layout/useMessageReceivers.ts, packages/visual-editor/src/internal/hooks/theme/useMessageReceivers.ts, packages/visual-editor/src/internal/hooks/useMessageReceivers.ts, packages/visual-editor/src/internal/utils/jsonFromEscapedJsonString.ts
`jsonFromEscapedJsonString` isn't necessary anymore and was actually breaking the editor if `"` was in a text field
Tested on a live site loading the editor with published+save state for layout+theme
=> fix: character escaping breaks editor

packages/visual-editor/src/components/TextList.tsx
Ran locally and verified that the sample text is only rendered when no field is mapped. Otherwise it will be the mapped value, even if empty.
=> fix: don't render sample text if field is mapped

packages/visual-editor/src/components/Address.tsx
Ran locally and verified that the component value default to the entity mapping.
=> fix: default address to entity value

packages/visual-editor/src/components/NearbyLocations.tsx
Show full address on cards instead of just line1
=> fix: adjust address in NearbyLocations 

packages/visual-editor/src/components/atoms/cta.tsx, packages/visual-editor/src/components/cards/EventCard.tsx, packages/visual-editor/src/components/cards/InsightCard.tsx, packages/visual-editor/src/components/cards/PersonCard.tsx, packages/visual-editor/src/components/contentBlocks/CtaWrapper.tsx, packages/visual-editor/src/components/contentBlocks/GetDirections.tsx, packages/visual-editor/src/components/pageSections/HeroSection.tsx, packages/visual-editor/src/components/pageSections/Promo.tsx
`"" ?? "#"` is `""`
`"" || "#"` is `"#"`
`<Link/> `from pages-components requires link for CTAs and empty strings do not count. Fixed and removed unneeded code.
=> fix: cta undefined 

packages/visual-editor/src/components/Directory.tsx, packages/visual-editor/src/components/atoms/index.ts, packages/visual-editor/src/components/atoms/visibilityWrapper.tsx, packages/visual-editor/src/components/layoutBlocks/Collection.tsx, packages/visual-editor/src/components/layoutBlocks/Flex.tsx, packages/visual-editor/src/components/layoutBlocks/Grid.tsx, packages/visual-editor/src/components/pageSections/Banner.tsx, packages/visual-editor/src/components/pageSections/Breadcrumbs.tsx, packages/visual-editor/src/components/pageSections/CoreInfoSection.tsx, packages/visual-editor/src/components/pageSections/FAQs.tsx, packages/visual-editor/src/components/pageSections/HeroSection.tsx, packages/visual-editor/src/components/pageSections/NearbyLocations.tsx, packages/visual-editor/src/components/pageSections/PhotoGallerySection.tsx, packages/visual-editor/src/components/pageSections/Promo.tsx, packages/visual-editor/src/components/pageSections/SectionContainer.tsx, packages/visual-editor/src/components/registry/components.ts
On show, no changes from normal. On hide, in live page and preview it won't show up at all and in editor it has opacity-30 with an slashed eyeball icon floating.
=> feat: add liveVisibility prop to Promo

packages/visual-editor/src/components/cards/ProductCard.tsx
Cta is now type CTA not string and image props are now available so layout (auto or fixed) can be chosen as well as the other imageWrapperProps. https://jam.dev/c/41941ca3-41ac-44a4-bdf5-bb29efe10720
=> fix: adjust Product Card props

packages/visual-editor/src/components/layoutBlocks/Collection.tsx
When the Collections component is set to "Entity" instead of Constant Value, we hide the options for Grid and Flex.
However they were still being applied.
We only want the Flex behavior while in entity mode.
Using Grid layout in entity mode causes the cards to all get squished.
=> fix: fix Collection "grid" mode applying in entity mode

packages/visual-editor/src/editor/YextEntityFieldSelector.tsx, packages/visual-editor/src/internal/puck/constant-value-fields/ImageList.tsx
No clue how I missed this, but now when you select const, you can actual adjust the array of const images.
=> fix: adjust PhotoGallery to supports constant

packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
When I was playing around with PhotoGallery, I noticed puck's array field (available when const value is toggled) wasn't updating the ui properly. Now fixed.
=> fix: adjust YextEntityFieldSelector

packages/visual-editor/src/components/pageSections/HeroSection.tsx
In the Hero component, we have two CTAs
If one is set to Link and the other a button style, then the Link will appear offset to the bottom.
This adds "py-3" to both of the CTAs to ensure that they both have it, even when in "Link" style.
This makes things stay aligned without affecting buttons in other places.
Fixed: 
Broken:
=> fix: hero link misalignment

packages/visual-editor/src/components/pageSections/PhotoGallerySection.tsx
Ah so React is dumb and images?.length is falsy but it decides to render 0 like in screenshot. Google says if your condition is falsy, it doesn't return the second argument (<CarouselProvider/>), but instead will return images?.length, which is a number, so react will render it because React skips rendering for anything that is typeof boolean or undefined
Fixed so now images && images.length > 0 is the conditional so its a boolean and React renders nothing.
=> fix: photoGallery returning zero

packages/visual-editor/THIRD-PARTY-NOTICES, packages/visual-editor/package.json, packages/visual-editor/src/utils/index.ts, packages/visual-editor/src/utils/searchHeadlessConfig.ts, packages/visual-editor/src/vite-plugin/templates/edit.tsx, packages/visual-editor/src/vite-plugin/templates/main.tsx, pnpm-lock.yaml, starter/src/components/Locator.tsx, starter/src/templates/dev.tsx
This will attempt to read the environment variables off of the entity document in order to get the values needed to set up Search Headless.
Remaining work to be done:
- read experience key from entity document (waiting on Spruce work)
- move logic to locator-specific template
- actually set the env vars in the site when creating the first locator page set
J=[WAT-4782](https://yexttest.atlassian.net/browse/WAT-4782?atlOrigin=eyJpIjoiZTRkYWYwMzNhZDUwNGExNGIwMDkzNTU5NDQ0OTNmNjUiLCJwIjoiaiJ9)
TEST=manual
Used dev account in development mode and saw us attempt to read from the env vars
=> feat: use document env vars to set up search headless

packages/visual-editor/src/vite-plugin/templates/edit.tsx
Adds fullstory capture to the edit page
Testing: Created a branch with a self-packed version of VE. Swapped to that branch on a prod account that is not excluded from reporting. Logged out of admin2 and then into the platform as a user created from the email signup flow. After waiting at least 30 minutes for my fullstory session to populate, checked with Duval (who has access to fullstory) and confirmed the iframed content was visible)
=> feat: support fullstory in editor iframe

packages/visual-editor/src/components/pageSections/HeroSection.tsx, packages/visual-editor/src/editor/YextEntityFieldSelector.tsx, packages/visual-editor/src/internal/puck/constant-value-fields/CallToAction.tsx, packages/visual-editor/src/internal/puck/constant-value-fields/HeroSection.tsx, packages/visual-editor/src/internal/utils/getFilteredEntityFields.ts, packages/visual-editor/src/types/entityFields.ts, packages/visual-editor/src/types/index.ts, packages/visual-editor/src/types/types.ts
Updated HeroSection to no longer map to individual entityFields but instead map to one new built-in field we are adding which is `type.hero_section` which includes the image, primaryCta, and secondaryCta
[video](https://jam.dev/c/cf81cf87-3d89-47f0-abbb-33a92f65eb84)
=> feat: update heroSection

packages/visual-editor/src/components/pageSections/CoreInfoSection.tsx
This used to work, but at some point didn't work again. Fixed so if no services, hides the services column. Same for hours
=> fix: hide columns in CoreInfoComponent if no data

packages/visual-editor/src/components/Directory.tsx, packages/visual-editor/src/components/atoms/heading.tsx, packages/visual-editor/src/components/pageSections/EventSection.tsx, packages/visual-editor/src/components/pageSections/InsightSection.tsx, packages/visual-editor/src/components/pageSections/ProductSection.tsx, packages/visual-editor/src/components/pageSections/TeamSection.tsx, packages/visual-editor/src/components/pageSections/TestimonialSection.tsx
For WCAG, the headers inside the cards that are in one of our list sections (Event, Insight, Product, Team, Testimonial) should be one heading level under than the Section Heading, regardless of their styling
=> fix: card heading levels

packages/visual-editor/src/internal/utils/getFilteredEntityFields.ts, packages/visual-editor/src/types/entityFields.ts, starter/localData/dev-location-stream__en__8573da7e3961090ddb59214a1f01e59a.json, starter/localData/dev-location-stream__en__a5ac5ff0d6330870779568c3bc865bc7.json, starter/localData/dev-location-stream__en__aa6fc9407fdca53fc4133ee078b93231.json, starter/localData/dev-location-stream__en__cbafb9cd1c3e63d9814e236ba9181377.json, starter/localData/dev-location-stream__en__d7f52f17aa2a321e60e8c1a8fae53637.json, starter/src/dev.config.ts
Adds support for `type.boolean`
`type.option` returns for `type.option` and `type.string` unless the `expandOptionFields` has been applied, in which case it only returns for `type.option`
Multi-option has the same behavior but with `includeListsOnly:true`
https://github.com/user-attachments/assets/f785f5b5-0fa0-4272-b235-f49a8e663998
=> feat: support boolean and option with YextEntityField

packages/visual-editor/src/components/Directory.tsx, packages/visual-editor/src/components/pageSections/NearbyLocations.tsx
`text-body-fontSize-sm` isn't a valid class name (`text-body-sm-fontSize` is). These two components aren't using the `sm` variant in the mocks anyway
=> fix: remove text-body-fontSize-sm

packages/visual-editor/src/components/cards/ProductCard.tsx, packages/visual-editor/src/components/pageSections/InsightSection.tsx, packages/visual-editor/src/components/pageSections/ProductSection.tsx, packages/visual-editor/src/components/pageSections/TestimonialSection.tsx
1. Set an aspect ratio so Insights don't get really tall
2. Add grow to Testimonial so the card fills the border height
3. Update border radii to match mocks
Before
After
=> fix: small component updates

.github/workflows/check-migrations.yml, packages/visual-editor/src/components/migrations/README.md
Adds a github action that checks if component files have been updated. If they have and migrations have not, a comment is added to the PR with a warning. Doesn't actually check for anything other than files being updated so it's far from comprehensive but may be a helpful nudge?
See example here: #461 (the first commit had component changes but no migration, the second commit component+migration changes, and the third no component changes)
=> feat: add migration check

packages/visual-editor/src/components/atoms/image.tsx, packages/visual-editor/src/components/pageSections/InsightSection.tsx, packages/visual-editor/src/components/pageSections/ProductSection.tsx
Thread: https://yext.slack.com/archives/C06A06BCUUF/p1747766568494449?thread_ts=1747680405.497999&cid=C06A06BCUUF
- Standardizes image size and adds a placeholder if the image doesn't exist on desktop
- Pushes the CTA to the end of the card 
This isn't perfect / I'm sure there will be more changes at some point, but I think this handles it better
https://github.com/user-attachments/assets/54835842-2d4c-455c-8aba-ab0ef9d88f0d
=> refactor: handle missing data in Insights and Products

packages/visual-editor/src/components/_componentCategories.ts, packages/visual-editor/src/components/pageSections/FINS/FINS_InsuranceSection.tsx, packages/visual-editor/src/components/registry/components.ts, packages/visual-editor/src/editor/YextEntityFieldSelector.tsx, packages/visual-editor/src/internal/puck/constant-value-fields/InsuranceProvidersSection.tsx, packages/visual-editor/src/internal/utils/getFilteredEntityFields.ts, packages/visual-editor/src/types/fields.ts, packages/visual-editor/src/types/types.ts
Created Insurance Providers component for FINS.
Component is added under `components/pageSections/FINS`
Didn't add it to `/pageSections/index.ts`
Created a new Struct and Constant for `InsuranceProviders`
[Component Doc](https://docs.google.com/document/d/15JdCygk76PxQXL9z3OcFBDCdMWGYyrvyIWDMZA0U_18/edit?tab=t.ghh9n42jhwbs)
=> feat: added Insurance providers Section for FINS

packages/visual-editor/generateFontRegistry.js, packages/visual-editor/src/components/testing/componentTests.setup.ts, packages/visual-editor/src/utils/font_registry.js, packages/visual-editor/src/utils/visualEditorFonts.ts
1. We weren't differentiating between variable and static fonts, so static fonts with multiple weights were being requested like variable fonts, leading to missing font files.
Before
After
(the search icon seems to be different in platform vs in the fake starter, will look into separately)
2. Each component test loaded every font. Only loading Open Sans significantly reduced test time, hopefully eliminating flaky timeouts
=> fix: handle static fonts with multiple weights

packages/visual-editor/src/vite-plugin/templates/main.tsx
This appends `-{entityId}` on the path built from address. Was requested from aaron so there aren't as many path conflicts when entities have the same address (and no slug)
=> feat: adjust paths in main template

packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
The current components only use RTF as part of a section but the FINS components use RTF directly. To enable constant values for that field, we should map RTF to the normal string constant value input. MaybeRTF can handle a plain string so the output should be type safe.
=> feat: use string constant value for RTF

packages/visual-editor/src/components/pageSections/FINS/FINS_DisclosureSection.tsx
Updated description filtering to support both `string` and `rich_text_v2`, which was a missed in the previous PR.
=> fix: added rtf2 to description

packages/visual-editor/src/editor/EntityField.tsx, packages/visual-editor/src/internal/puck/ui/Tooltip.tsx
Updates the entity field tooltip size based on the viewport size/zoom. Uses similar logic to how puck scales the component name in the action bar.
https://github.com/user-attachments/assets/8b1a1b11-0c3c-4018-9a0c-55bf9e09d329
=> feat: resize tooltips based on viewport

packages/visual-editor/src/components/Locator.tsx, packages/visual-editor/src/utils/searchHeadlessConfig.ts
We will use an environment-wide Mapbox key (in the `YEXT_EDIT_LAYOUT_MODE_MAPBOX_API_KEY` env var) when in the VLE iframe in order to get around the URL restrictions by the site-specific API key. If this key is not present for some reason, we will fall back to the site-specific API key. 
J=[WAT-4873](https://yexttest.atlassian.net/browse/WAT-4873)
TEST=manual
=> feat: use YEXT_EDIT_LAYOUT_MODE_MAPBOX_API_KEY when in VLE if present

packages/visual-editor/src/components/atoms/hoursStatus.tsx, packages/visual-editor/src/components/contentBlocks/HoursStatus.tsx, packages/visual-editor/src/components/pageSections/HeroSection.tsx, packages/visual-editor/src/components/pageSections/NearbyLocations.tsx
Updated to use the translation hook that is set based on the document locale. Also added format conversion for the time for countries that use 24hr notation.
https://github.com/user-attachments/assets/e0df1e61-fadd-483d-9168-6b5a0c21640f
=> refactor: enable locales in hours status

packages/visual-editor/src/components/contentBlocks/Emails.tsx, packages/visual-editor/src/components/pageSections/CoreInfoSection.tsx
If a list length was already set, it would previously still use that length even in constant value mode. This ensures it ignores the length in constant value mode.
=> fix: ignore email list length in constant value mode

packages/visual-editor/src/components/Locator.tsx
The path creating logic was changed in the main template, but not in our Locator component, so the links were no longer pointing to the correct path. Here I have updated the logic to be the same as the main template
=> fix: fix path logic for linked entities

.gitattributes
I'm not sure if this is better but we might want can auto-hide the translation diffs? I wish they appeared smaller
=> chore: hide translation diffs

packages/visual-editor/scripts/generateFontRegistry.js, packages/visual-editor/src/utils/font_registry.js
These two fonts seem to have slightly different options on Google vs. Cloudflare. Added a (hopefully) temporary override to ensure the entire font list requests from Cloudflare.
=> refactor: add overrides for specific problem fonts

packages/visual-editor/src/components/contentBlocks/MapboxStaticMap.tsx
This limits the mapbox height and width to the size limits defined here: https://docs.mapbox.com/api/maps/static-images/#retrieve-a-static-map-from-a-style
=> fix: limit mapbox size

packages/visual-editor/src/components/header/languageDropdown.tsx
Now when you toggle locales in the editor (layout and theme), the language dropdown selected value changes as well.
=> fix: default language dropdown value in Editor

packages/visual-editor/src/utils/applyTheme.test.ts, packages/visual-editor/src/utils/applyTheme.ts, packages/visual-editor/src/utils/visualEditorFonts.test.ts, packages/visual-editor/src/utils/visualEditorFonts.ts, packages/visual-editor/src/vite-plugin/templates/edit.tsx
Before:
Would inject every single font option
Now: 
Only injects fonts being used in the theme
Confirmed on site [here](https://www.yext.com/s/4412098/yextsites/158910/pagesets) that live pages have correct style tags and Layout Editor / Theme Editor work. Theme Editor also has all the font options still and changing fonts works as expected.
=> fix: reduce fonts imported into generated pages

packages/visual-editor/src/internal/puck/ui/button.tsx
Button types "ghost" and "link" use ve-font-medium
The others default to normal
This matches the Figma mocks
=> fix: set default button font to font-normal

packages/visual-editor/src/components/pageSections/HeroSection.tsx, packages/visual-editor/src/components/pageSections/PromoSection.tsx
The width set in props usually exceeds the mobile screen width. I think there's still some adjustments to make because the new system is not very responsive but this makes it less messy for mobile sites
Before:
After:
https://github.com/user-attachments/assets/691e6d3a-d604-46ac-b7c7-303da8cec286
=> fix: update hero/promo images on mobile

packages/visual-editor/src/components/atoms/heading.tsx
When the section heading is h6, the subheadings are spans. These should display: block so they render the same as headings
Before:
After:
=> fix: display heading spans as block

.github/workflows/unit_test.yml
> Using variable interpolation `$...` with `github` context data in a `run:` step could allow an attacker to inject their own code into the runner. This would allow them to steal secrets and code. `github` context data can have arbitrary user input and should be treated as untrusted. Instead, use an intermediate environment variable with `env:` to store the data and use the environment variable in the `run:` script. Be sure to use double-quotes the environment variable, like this: "$ENVVAR".
=> chore: unit test action vulnerability 

packages/visual-editor/THIRD-PARTY-NOTICES, packages/visual-editor/package.json, packages/visual-editor/src/internal/puck/constant-value-fields/Phone.tsx, packages/visual-editor/src/internal/puck/ui/puck.css, pnpm-lock.yaml
We're phasing out uses of libphonenumber-js across Yext Github repos, and visual editor depends transitively on this library in through react-phone-number-input.
Swap over to react-international-phone and update styling overrides.
TEST=manual
test against visual-editor/starter and run against a sandbox account in & out of DevMode for
comparison.
react-international-phone has the expected style overrides and formats numbers comparably.
**Before**:
**After**:
=> chore: swap react-phone-number-input to react-international-phone

packages/visual-editor/src/internal/hooks/useMessageReceivers.ts, packages/visual-editor/src/utils/filterComponents.tsx, packages/visual-editor/src/vite-plugin/templates/main.tsx
This PR adds support for category filtering.
Slack thread for additional context: https://yext.slack.com/archives/C06A06BCUUF/p1754493867337909
J=WAT-5002
TEST=manual
referenced this packed version in a starter branch and tested in platform.
1. When the product feature is enabled, the core info category and its atoms appear in the Components column of the Editor. User can drag the grid and subcomponents onto the page.
2. When the product feature is disabled, the core info category and its atoms are hidden the Components column. Any existing grid sections already placed on the page will show a "No configuration" message in the Editor. These sections will not appear on the live site.
3. Currently, the atoms under the core info category are exclusive to that category. However, tested …
=> feat: support category filtering

packages/visual-editor/src/internal/components/InternalLayoutEditor.tsx
This ensures that both Radio and Select options are translated in the editor.
=> fix: translate select options

packages/visual-editor/src/editor/YextEntityFieldSelector.tsx
This mirrors logic in `packages/visual-editor/src/editor/TranslatableStringField.tsx` that converts old-style basic strings into TranslatableStrings
=> fix: embedded field conversion

packages/visual-editor/src/internal/puck/constant-value-fields/ImageOrVideo.tsx
The AutoField wouldn't always react to the type change. Adding a key makes it work
=> fix: image/video toggle

packages/visual-editor/locales/de/visual-editor.json
The current German translation means more like
'open \<this\> now' instead of the intended
'\<things which are\> open now'. This small change
adjusts that.
=> fix: correct German 'open now' translation

packages/visual-editor/src/components/contentBlocks/Phone.tsx, packages/visual-editor/src/components/pageSections/CoreInfoSection.tsx
Original steps to reproduce problem: 
1. Drag in the CoreInfoSection
2. Delete the existing phone item in the phone numbers array field
3. Add a new phone item 
4. Attempt to edit or change the phone data 
5. Bombs out b/c the default phone props in the array were invalid 
Tested locally and confirmed is fixed.
=> fix: phoneNumbers in CoreInfoSection bombing out

packages/visual-editor/src/internal/components/AdvancedSettings.tsx, packages/visual-editor/src/utils/getSchema.ts
When sending the user's schema to the parent to allow for editing, we now also send the default schema. A new option in the UI will allow the user to restore the default schema and clear any edits they've made.
Ran everything locally and logged the payload that was sent to the front-end, confirming that it included the new defaultValue field.
=> feat: provide default schema to parent window
